import type { WorkspaceActionLabels, WorkspaceConfig, WorkspaceDeskLabels } from "@/app/_lib/org/types";

/**
 * Demo workspace config (not active by default).
 * Purpose: validate the app can be driven fully by config with a single switch.
 */
export const demoNgoWorkspaceConfig: WorkspaceConfig = {
  id: "demoNgo",
  locale: "en",
  theme: "light",
  branding: {
    productName: "Blue Team Secure Desk",
    workspaceName: "Demo NGO Workspace",
    workspaceShortName: "Demo NGO",
    workspaceType: "Case Desk",
    dashboardTitle: "Demo NGO Case Desk",
    productOwner: "Blue Team Africa",
    workspaceLogoPath: "/editorial/sf1.png",
  },
  labels: {
    itemSingular: "case",
    itemPlural: "cases",
    inbox: "Inbox",
    assignments: "Assigned",
    myQueue: "Your queue",
    analytics: "Analytics",
    settings: "Settings",
    managingEditorDesk: "Managing Editor Desk",
    newsroomOperations: "Operations overview",
    managingEditorDeskSubline: "A quick operational sweep across the room.",
    runSheet: "Run sheet",
    activeReports: "Inbox",
    new: "New",
    needsTriage: "Needs triage",
    withLead: "With lead",
    inReview: "In review",
    awaitingFollowUp: "Waiting follow-up",
    resolved: "Resolved",
    archive: "Archive",
    noLeadYet: "No lead yet",
    needsALead: "Needs a lead",
    resolvedToday: "Resolved today",
    onTheBooks: "On the books",
    unclaimedPickTheseUpFirst: "Unclaimed — pick these up first",
    roleLabels: {
      owner: "Editor in Chief",
      admin: "Managing Editor",
      reviewer: "Editor",
      intake: "Proofreader",
      readonly: "Viewer",
    },
    caseStatusLabels: {
      incoming: "New",
      raw: "Needs triage",
      first_edit: "With lead",
      second_edit: "In review",
      in_review: "Waiting follow-up",
      reviewed: "Resolved",
      designed: "Archive",
    },
  },
  workflow: {
    // Demo: slightly different ordering to prove config-driven templates.
    stageOrder: ["incoming", "raw", "second_edit", "first_edit", "in_review", "reviewed", "designed"],
    sidebarStageViews: [
      { key: "needs_lead", href: "/dashboard?view=needs_lead" },
      { key: "assigned_work", href: "/dashboard?view=assigned_work" },
      { key: "new", href: "/dashboard?view=incoming" },
      { key: "needs_triage", href: "/dashboard?view=raw" },
      // Demo: surface review before lead stage in the sidebar order.
      { key: "in_review", href: "/dashboard?view=second_edit" },
      { key: "assigned", href: "/dashboard?view=first_edit" },
      { key: "waiting_follow_up", href: "/dashboard?view=in_review" },
      { key: "resolved", href: "/dashboard?view=reviewed" },
      { key: "archive", href: "/dashboard?view=designed" },
      { key: "team", href: "/dashboard?view=team" },
      { key: "analytics", href: "/dashboard?view=analytics" },
    ],
    mePipelineStages: ["incoming", "raw", "second_edit", "first_edit", "in_review"],
    viewKeyByStatus: {
      incoming: "new",
      raw: "needs_triage",
      first_edit: "assigned",
      second_edit: "in_review",
      in_review: "waiting_follow_up",
      reviewed: "resolved",
      designed: "archive",
    },
  },
  integrations: {
    exportProvider: "manualDownload",
    oneDrive: {
      enabled: false,
      rootFolderName: "Demo Secure Desk",
      stageFolderMap: {
        incoming: "01 Intake",
        raw: "02 Triage",
        first_edit: "03 Assigned",
        second_edit: "04 Review",
        in_review: "05 Follow-up",
        reviewed: "06 Resolved",
        designed: "07 Archive",
      },
    },
  },
  deskLabels: {
    leadNoun: "case officer",
    reporterNoun: "source",
    withLabel: "Assigned to",
    filedByLabel: "Filed by",
  } satisfies WorkspaceDeskLabels,
  actionLabels: {
    open: "Open",
    download: "Download",
    downloading: "Downloading…",
    opening: "Opening…",
    exportDocx: "Export case file",
    exportingDocx: "Preparing export…",
    applyStageChange: "Apply stage change",
    updateStatus: "Update status",
    saveTriageNote: "Save triage note",
    saveDeskNote: "Save case note",
    saveNewsroomNote: "Save case note",
    saveInternalNote: "Save case note",
    setLead: "Assign case officer",
    assign: "Assign case officer",
    markHighPriority: "Flag urgent",
    resolve: "Close",
    archive: "Close / Archive",
    delete: "Delete case",
    deleteEllipsis: "Delete case…",
    deleteKeep: "Keep this case",
    deletePermanently: "Delete permanently",
    deleteConfirmBody:
      "This permanently deletes this case record by deleting the Firestore document. Anyone viewing it will lose access. This cannot be undone.",
  } satisfies WorkspaceActionLabels,
  priorityLabels: {
    urgent: "Urgent",
    highAttention: "High attention",
  },
  detailSectionLabels: {
    reporterSectionTitle: "Source",
    filingSectionTitle: "From the source",
    attachmentsSectionTitle: "Attachments",
    notesHintTriage: "Short triage context (shared staff notes field).",
    notesHintDesk: "Visible only to staff — not to the source.",
    notesHintManagingEditor: "Visible only to staff — never shared back to the source.",
    notesHintDefault: "Staff-only notes — not visible to the source.",
    detailMetaTitleEditor: "Case file",
    detailMetaTitleManagingEditor: "Case file & routing",
    detailMetaTitleDefault: "Case details",
    detailMetaSubmitted: "Reported",
    detailMetaUpdated: "Updated",
    detailMetaDeskLine: "Desk line",
    detailMetaWorkflowStatus: "Workflow status",
    detailMetaHowItArrived: "How it arrived",
    detailMetaSourceChannel: "Source channel",
    detailActionsTitleEditor: "Next steps",
    detailActionsTitleManagingEditor: "Workflow control",
    detailActionsTitleDefault: "Actions",
    detailActivityTitleEditor: "Activity",
    detailActivityTitleManagingEditor: "Desk log",
    detailActivityTitleDefault: "Audit / activity",
    detailActivityBodyEditor: "Activity history will appear here once enabled.",
    detailActivityBodyManagingEditor: "A rolling log will appear here once activity tracking is enabled.",
    detailActivityBodyDefault: "Activity history will appear here once enabled.",
    decryptLoading: "Opening the filing…",
    activityLoading: "Loading activity…",
    activityEmpty: "No activity yet.",
    noReporterLetter: "No source letter was stored for this submission.",
    noBodyText: "No body text was found in this filing.",
    titleAsFiled: "Title as filed",
    theirWords: "Their words",
  },
  exportDocxLabels: {
    filedBy: "Filed by",
    status: "Status",
    attachments: "Attachments",
    generatedByPrefix: "Generated by",
  },
  chrome: {
    poweredByPrefix: "Powered by",
    editorDeskSidebarTitle: "Editor desk",
    navSectionYourDesk: "Your desk",
    navSectionQueues: "Queues",
    navSectionMenu: "Menu",
    teamNavManagingEditor: "Team roster",
    teamNavDefault: "Team",
    sidebarSuspenseFallbackBadge: "SR",
    sidebarSuspenseFallbackSubtitle: "Case management",
    editorDeskHeaderSuspenseTitle: "Editor desk",
    editorDeskHeaderSuspenseSubtitle: "Work the desk clearly and move filings forward.",
    intakeTopbarTitle: "News desk",
    intakeTopbarSubtitle: "Route tips, keep the trail clear, move work forward.",
  },
  editorDeskHeaders: {
    default: { title: "Editor desk", subtitle: "Work the desk clearly and move filings forward." },
    byInferredView: {
      inbox: { title: "Inbox", subtitle: "All visible filings across the desk." },
      raw: { title: "New", subtitle: "New incoming material waiting for movement." },
      new: { title: "New", subtitle: "New incoming material waiting for movement." },
      "raw-materials": { title: "New", subtitle: "New incoming material waiting for movement." },
      edit1: { title: "Needs triage", subtitle: "Stories currently in the first editorial pass." },
      "first-editing": { title: "Needs triage", subtitle: "Stories currently in the first editorial pass." },
      needs_triage: { title: "Needs triage", subtitle: "Stories currently in the first editorial pass." },
      assigned: { title: "Your queue", subtitle: "Items currently on your desk." },
      "your-queue": { title: "Your queue", subtitle: "Items currently on your desk." },
      proof: { title: "In review", subtitle: "Copy and correction stage." },
      proofreading: { title: "In review", subtitle: "Copy and correction stage." },
      in_review: { title: "In review", subtitle: "Copy and correction stage." },
      design: { title: "Waiting follow-up", subtitle: "Stories currently in design." },
      designed: { title: "Waiting follow-up", subtitle: "Stories currently in design." },
      waiting_follow_up: { title: "Waiting follow-up", subtitle: "Stories currently in design." },
      published: { title: "Resolved", subtitle: "Released pieces kept visible for reference." },
      resolved: { title: "Resolved", subtitle: "Released pieces kept visible for reference." },
      archive: { title: "Archive", subtitle: "Past work retained for search and review." },
      archived: { title: "Archive", subtitle: "Past work retained for search and review." },
    },
  },
  detailInspector: {
    detailRoomSnapshotTitle: "Snapshot",
    detailRoomCheckTitle: "Room check",
    detailOverviewTitle: "Overview",
    notesTriageTitle: "Triage notes",
    notesDeskTitle: "Desk notes",
    notesNewsroomTitle: "Newsroom notes",
    notesInternalTitle: "Internal notes",
    emptyPanelTitleEditor: "Your queue",
    emptyPanelTitleManagingEditor: "Command center",
    emptyPanelTitleDefault: "Pick a case",
    emptyPanelSubtitleEditor: "One story at a time — tap a card to work it.",
    emptyPanelSubtitleManagingEditor: "Choose a card to steer leads, stages, and the full filing.",
    emptyPanelSubtitleDefault: "Select a card to read, route, and close the loop.",
    emptyPanelBodyEditor:
      "Cards are ordered for focus. Open one to see the summary, the reporter’s words, and your desk notes together.",
    emptyPanelBodyManagingEditor:
      "The board is live. Open any card to move ownership, shift stages, or read what came in from the field.",
    emptyPanelBodyDefault: "Tap a card to read what came in, coordinate with the team, and keep the trail clean.",
  },
  runSheet: {
    runSheetAriaLabel: "Newsroom run sheet",
    runSheetIntroLede:
      "Live counts from your queue — who still needs a lead, what is in motion, and where work is stacking.",
    mePipelineInMotionLabel: "In motion",
    mePipelineInMotionHint: "Not resolved or archived",
    meOnTheBooksHint: "Everything not archived",
    meResolvedStillOpenLabel: "Resolved, still open",
    meResolvedStillOpenHint: "Ready to archive or file",
    meWhereItStacksTitle: "Where it stacks (in motion)",
    meBottleneckBalancedCopy: "No single stage is holding more than the rest right now.",
    meAssignmentStatusAriaLabel: "Assignment status",
    meAllClaimedMessage: "Every in-motion case already has someone on it.",
    meUnclaimedOverflowSuffix:
      " more in motion still need someone on them — scan Active reports or Needs triage in the queue.",
  },
  board: {
    emptyNoCasesTitleEditor: "Nothing on your desk yet",
    emptyNoCasesTitleManagingEditor: "The wire is quiet",
    emptyNoCasesTitleDefault: "No cases yet",
    emptyNoCasesBodyEditor:
      "When the desk assigns a submission to you, it will land here. Check back after the next routing round.",
    emptyNoCasesBodyManagingEditor:
      "When tips start filing, they will appear here with live leads and stages so you can steer the room.",
    emptyNoCasesBodyDefault: "When a new case arrives, it will appear here for your team to work on.",
    emptyReviewerNothingAssignedTitle: "Nothing assigned to you right now",
    emptyReviewerNothingAssignedBody:
      "Your list only shows submissions where you are the lead. If you expected work here, ask the desk to confirm the assignment — they may still be routing it.",
    intakeEmptyTitle: "Nothing in triage",
    intakeEmptyBeforeStates: "Intake only sees reports in ",
    intakeEmptyStateNewLabel: "New",
    intakeEmptyOrWord: " or ",
    intakeEmptyStateTriageLabel: "Needs Triage",
    intakeEmptyAfterStates: ". When submissions arrive in those states, they will appear here.",
    viewEmptyMyQueueTitle: "Nothing is assigned to you right now.",
    viewEmptyMyQueueBody: "When you're set as the lead on a report, it will show up here for quick access.",
    viewEmptyAssignedWorkTitle: "No assigned work right now.",
    viewEmptyAssignedWorkBody: "Items that already have a lead.",
    viewEmptyNeedsLeadTitle: "No items need a lead right now.",
    viewEmptyNeedsLeadBody: "Unclaimed items waiting for assignment.",
    viewEmptyWithLeadBody: "Assigned work will appear here once a lead is set.",
    viewEmptyResolvedBody: "When work is filed as resolved, it will appear here.",
    viewEmptyArchiveBody: "When items are archived, they will appear here.",
    viewEmptyActiveReportsBody:
      "Switch queues on the left or wait for new filings — the run sheet above still reflects the whole room.",
    viewEmptyQueueClearTitle: "This queue is clear",
    viewEmptyDefaultTitle: "Nothing in this view",
    viewEmptyDefaultBody: "Try another tab on the left, or check back as cases move through the workflow.",
    stageColumnTitleDesk: "Where it stands",
    stageColumnTitleDefault: "Case status",
    leadColumnTitleDesk: "Who has it",
    leadColumnTitleDefault: "Owner",
    cardOpenLabel: "Open",
    cardAssignLabel: "Assign",
  },
  team: {
    teamPageTitle: "Team",
    teamRosterLimitedBody: "Team roster is limited to owner and administrator roles in this workspace.",
    teamPageIntro:
      "A simple picture of who is in this workspace today. Invitations and roster editing will arrive in a later phase.",
  },
};

